### ISSUE TITLE
api versions are outdated in package templates

### ISSUE THREAD

**Issue by mkosak-sf** [forcedotcom/commerce-on-lightning#107]
The versions used in quickstart config store templates have outdated API versions and the version as far as I can tell doesn't get overwrriten when using template to create the actual package.xml file.  I believe version should be a part of the 'template' and get overriden with the value specified in devhub config.

**Comment by trinasfdx** [comment]
@W-11934133

**Comment by joeluong-sfcc** [comment]
Hi @mkosak-sf I believe this issue was resolved with this PR: https://github.com/forcedotcom/commerce-on-lightning/pull/130 so I will be closing this issue
