### ISSUE TITLE
commerce plugin throws error in sfdx-cli

### ISSUE THREAD

**Issue by smayers70** [forcedotcom/commerce-on-lightning#15]
Hi - we are a very small shop and was thrilled to find this plugin to speed our deployment of new stores into sandboxes. 

I'm a bit of a noob but I've been struggling all day to get sfdx commerce:store:create to run (throws an error about users)

However, it would seem the root error is that the plugin itself is now causing general errors in sfdx.  Screen shot attached.  

Steps to repro:
1. install sfdx cli using the package from salesforce (MacOS)
2. sfdx plugins (no plugins installed) <- no errors
3. sfdx plugins:install @salesforce/commerce <- throws some errors during install
4. Any command after this references an error in sfdx-cli properties_1.CONFIG_DIR

I have completely removed all previous versions of sfdx, npm node.js, etc from my machine to no avail.  Help!

Thank you!
![Screen Shot 2021-07-09 at 3 19 00 PM](https://user-images.githubusercontent.com/69163986/125126868-b97da680-e0c9-11eb-9245-fcde8265bc06.png)

**Comment by jarndt-ltm** [comment]
@smayers70 This should be fixed now

**Comment by smayers70** [comment]
thank you!
