### ISSUE TITLE
"The specified template does not exist" at commerce:store:create

### ISSUE THREAD

**Issue by syunyama** [forcedotcom/commerce-on-lightning#161]
When I ran command below,
```
sfdx commerce:store:create -n 1commerce -o b2c -u sampleScratch -v DevHub -b samplebuyer@1commerce.com
```

I got error:
```
"The specified template does not exist."
```

#### Suggested Solution

`B2B Commerce (LWR)` should be `B2B Commerce Template` in [b2b-store-scratch-def](https://github.com/forcedotcom/commerce-on-lightning/blob/develop/config/b2b-store-scratch-def.json#L4), as I see [ui-commerce-components](https://git.soma.salesforce.com/communities/ui-commerce-components/blob/main/packages/b2b-storefront/package.json#L5)

**Comment by joeluong-sfcc** [comment]
This is also most likely due to being on v56 as discussed in this issue: https://github.com/forcedotcom/commerce-on-lightning/issues/160

**Comment by syunyama** [comment]
@joeluong-sfcc 
Thank you.
 I will use v57 and close this this issue.
