### ISSUE TITLE
Feature Request: Command for uploading images to CMS and map them to product images

### ISSUE THREAD

**Issue by syunyama** [forcedotcom/commerce-on-lightning#164]
It seems [CMS Contents API](https://developer.salesforce.com/docs/atlas.en-us.chatterapi.meta/chatterapi/connect_resources_cms_contents.htm) can upload binary data from v56.
So it might be possible to upload images and map them to product images by creating ProductMedia object.

**Comment by tarcang** [comment]
Hello @syunyama , this feature would be out of scope for our plugin. We just create an Experience Site, I think it wouldn't be a good idea to have to this mapping of images in our plugin independently. This could be added to Experience Cloud. If that is the case, then our plugin can have an option.
