### ISSUE TITLE
Missing test classes for LWC apex controllers

### ISSUE THREAD

**Issue by ranveer5289** [forcedotcom/commerce-on-lightning#165]
Certain apex controllers used by LWC doesn't have any test coverage. Is it possible to add proper test coverage for these apex classes? It will also act as a nice reference on how to actually write test classes for ConnectApi methods.

https://github.com/forcedotcom/commerce-on-lightning/tree/develop/examples/b2b/lwc/force-app/main/default/classes

**Comment by tarcang** [comment]
Hello, this should be filed with the domain teams in charge of the apex classes we deploy. We will keep an eye on this.
