### ISSUE TITLE
Better documentation needed

### ISSUE THREAD

**Issue by peterTrifecta** [forcedotcom/commerce-on-lightning#191]
In looking at the README file it is not clear what to do with this repo.  

I ran  `sfdx commerce:store:create --store-name test-store` since the description said "Comprehensive create and set up a store. ".  However, I got the error `ERROR running commerce:store:create:  This command requires a username. Specify it with the -u parameter or with the "sfdx config:set defaultusername=<username>" command.` which must be because I didn't run the command to create a scratch org first and/or because I didn't have a definition file set up, though I haven't modified this repo yet, so who knows????

The question is which one command or series of commands need to be run to start with nothing and then have a fully operational store, complete with products, users, and everything in a scratch org.  That should be near the top of the README.

**Comment by tarcang** [comment]
Hello @peterTrifecta , have you checked docs/setup-guide.md? It could be what you are looking for. That is our step-to-step guide to create a store using the commerce-on-lightning plugin.
