### ISSUE TITLE
Test Classes not Enough Code Coverage

### ISSUE THREAD

**Issue by Heather-Hanson** [forcedotcom/commerce-on-lightning#263]
Hello,

I'm not a full time developer and we just learned that we need to update the classes for the B2BSyncCheckInventory, B2BSyncPricing, and B2BSyncDelivery classes due to the decommission of the Heroku sample

I've located the updated code and things are working in sandbox, but I'm having trouble deploying to prod because the test classes do not have enough code coverage.  Can you make any recommendations as to what I can add to the test classes for each to get more coverage?

Thank you!

**Comment by lcrenshawSOA** [comment]
Hey! This is effecting us too from getting our store to go live. Any help would be very much welcomed as we are trying to get this store up ASAP.

**Comment by tarcang** [comment]
Hello, thank you for opening the issue! What is the test coverage that is seen right now @Heather-Hanson? In my system, I didn't hit a blocker with test coverage.

**Comment by tarcang** [comment]
Didn't get a reply.
